# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('mac', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
				('script_id', models.IntegerField()),
				('script', models.TextField()),
            ],
        ),
    ]
